### ISSUE TITLE
Doesn't clear how to use health check

### ISSUE THREAD

**Issue by kamorozov** [hyness/spring-cloud-config-server#113]
Hi!

I want to add health check for docker container, but container doesn't have `curl` and I don't know how to add.

My implementation:

Dockerfile:
```yml
FROM hyness/spring-cloud-config-server:4.0

HEALTHCHECK CMD curl --fail http://localhost:8888/actuator/health || exit 1 

COPY application.yml /config/
```

docker-compose:
```yml
version: '3'
services:
  config-server:
    platform: linux/amd64
    container_name: config-server
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8888:8888"
    environment:
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: ${REPO_URL}
      SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULTLABEL: ${BRANCH_NAME:-master}
      MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED: true
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "*"
    command:
      - --spring.cloud.config.server.git.search-paths=${STAND_NAME:-dev}
    healthcheck:
      test: curl --fail http://localhost:8888/actuator/health || exit 1
      interval: 60s
      retries: 5
      start_period: 30s
      timeout: 10s
```
<img width="1642" alt="image" src="https://github.com/hyness/spring-cloud-config-server/assets/13591599/7cabde50-57d0-47dd-a0e9-abe2c3f6042c">
