### ISSUE TITLE
/encrypt endpoint returns 401

### ISSUE THREAD

**Issue by vazuev** [hyness/spring-cloud-config-server#114]
Hello!

Endpoint /encrypt returns 401 when 
`spring.profiles.active: security` is active 

At the same time configs are returned unencrypted well.

Here is an example of configuration:

encrypt:
  key: ${CONF_SERVER_ENCRYPT_KEY}

```
encrypt:
  key: ${CONF_SERVER_ENCRYPT_KEY}
spring:
  security:
    user:
      name: ${CONF_SERVER_USER}
      password: ${CONF_SERVER_PASSWORD}
  profiles:
    active: security
  cloud:
    config:
      server:
        prefix: /config
        git:
          uri: ${GIT_SERVER_URL}
          username: ${GIT_SERVER_USER}
          password: ${GIT_SERVER_PASSWORD}

```

And example curl:
```
curl --request POST \
  --url https://example.com/config/encrypt \
  --header 'Authorization: Basic XXXXXXXXXXX' \
  --header 'Content-Type: text/plain' \
  --cookie JSESSIONID=DF9460027A313F21E4CCB650F0B8857F \
  --data geOtIO
```
