### ISSUE TITLE
Container fails - healthEndpointWebMvcHandlerMapping thows exception

### ISSUE THREAD

**Issue by wbrco** [hyness/spring-cloud-config-server#141]
Fails in :latest, :jdk17 and :jdk21 tags, regardless of starting via docker run or executing docker-compose up.

Docker run command:
`docker run -q -p 8888:8888 -v /home/allen/spring/config:/config -v /home/allen/spring/native-files:/native-files hyness/spring-cloud-config-server:jdk17|jdk21|latest`

docker-compose.yaml:
```
services:
  configserver:
    image: hyness/spring-cloud-config-server:latest
    volumes:
      - /home/allen/spring/config:/config
      - /home/allen/spring/native-files:/native-files
    ports:
      - "8888:8888"
   healthcheck:
      test: ["CMD", "health-check"]
      start_interval: 30s
      interval: 5s
      retries: 10
```
/home/allen/spring/config/application.yml:
```
spring:
  cloud:
    config:
      server:
        native:
         searchLocations: /native-files
  profiles:
    active: native
```

System info:
```
allen@awsenv:/etc$ cat debian_version
10.13
allen@awsenv:/etc$ uname -r
4.19.0-27-amd64
allen@awsenv:/etc$ docker -v
Docker version 26.1.4, build 5650f9b
```

[configserver.log](https://github.com/user-attachments/files/19797270/configserver.log)
