### ISSUE TITLE
support custom banner.txt

### ISSUE THREAD

**Issue by jangalinski** [hyness/spring-cloud-config-server#3]
I would love to mount a different banner.txt when the config server starts. should be possible by defining a volume mount.

**Comment by hyness** [comment]
As stated in the documentation, this is a normal Spring Boot application.  To set a custom banner you can use the `banner.location` property to set a custom banner.  Here is an example using environment variables...

```
docker run -it --name=spring-cloud-config-server \
      -p 8888:8888 \
      -v </path/to/config>:/config \
      -e BANNER_LOCATION=</path/to/banner.txt> \
      hyness/spring-cloud-config-server
```

**Comment by jangalinski** [comment]
Thanks for the advise. Using docker-compose, I was not able to achieve this. I tried:

```
configserver:
    image: hyness/spring-cloud-config-server:1.3.0.RELEASE
    environment:
      - SPRING_PROFILES_ACTIVE=native
      - BANNER_LOCATION=/config/.configserver-banner.txt
    ports:
      - "8888:8888"
    volumes:
      - ./configuration:/config
```

where my banner.txt is inside the mounted `/config` dir and called `.configserver-banner.txt`

any ideas how to fix this?
