### ISSUE TITLE
Reading the configuration via GCP Secret Manager does not work when running this image as Cloud Run Service

### ISSUE THREAD

**Issue by ichandan16** [hyness/spring-cloud-config-server#91]
Hi,

While running as a docker image as below it, works fine.

```
docker run -it -p 8888:8888 \
    -v /etc/springboot_configs/application.yaml:/config/application.yaml \
      hyness/spring-cloud-config-server:3.0.5
```

Invoking this command works and it fetches the values from the git.
`curl http://localhost:8888/spboot-sink/gcpnpr`

Now, I am trying to run this container to run as a [cloud run service](https://cloud.google.com/run/docs/configuring/secrets#mounting-secrets-service), and the `application.yaml` is provided as a secret and expected to work as a volume in the cloud run.

Here is how, I am running the cloud run command:

```
gcloud run deploy spring-cloud-config-server \
--image=us-west1-docker.pkg.dev/gcp-demo-prj/testrepo/spring-cloud-config-server@sha256:xxxxxxx \
--vpc-connector=projects/gcp-demo-prj/locations/us-west1/connectors/serverless-connector \
--allow-unauthenticated \
--port=8888 \
--service-account=xxxx-compute@developer.gserviceaccount.com \
--memory=1Gi \
--min-instances=1 \
--max-instances=2 \
--set-secrets=/config/application.yaml=configserver:latest \
--region=us-west1 \
--project=gcp-demo-prj
```

However it does not work. The the service running fine, I am not able to fetch the details from the git.

Appreciate any help on this.

**Comment by ichandan16** [comment]
Hi all, I got this thing working. Spring Cloud Config provides GCP Secret Manager as a backend but it is not documented anywhere. Here is the solution:
Add below dependency to pom.xml:

```
<dependency>
	<groupId>com.google.cloud</groupId>
	<artifactId>spring-cloud-gcp-starter-secretmanager</artifactId>
</dependency>
<dependency>
	<groupId>com.google.http-client</groupId>
	<artifactId>google-http-client-jackson2</artifactId>
	<version>1.40.1</version>
</dependency>
```
Set up your application.yml to secret-manager backend as below:

```
server:
  port: ${PORT:8080}
spring:
  application:
    name: config-server
  profiles:
    active: git,secret-manager
  cloud:
    config:
      server:
        gcp-secret-manager:
          application-label: application
          profile-label: profile
          token-mandatory: false
          order: 1
        git:
          uri: https://github.com/ichandan16/test-config-server.git
          order: 2
```
I had raised this issue in spring-cloud-config repo. 

https://github.com/spring-cloud/spring-cloud-config/issues/2148#issuecomment-1248396335
